version: '2'
services:
    carpadwebapp-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/carpadwebapp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=carpadwebapp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
